import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import type { AppContext } from '../context.js';
import type { CountryRef } from '../providers/types.js';
import { countryInput, yearFromInput, yearToInput } from '../schemas/common.js';
import { linearRegression, yearOverYear } from '../shared/stats.js';
import { toMermaid } from '../viz/mermaid.js';
import { formatNumber, markdownTable } from '../viz/table.js';
import {
  aggregateByYear,
  datasetProvenance,
  defaultYearRange,
  defineTool,
  fetchAllRows,
  latestAggregates,
  metricSeries,
  reportProgress,
  resolveCountry,
} from './common.js';

/**
 * Compose a full markdown country report from the population, asylum and
 * demographics datasets. Emits MCP progress notifications while it works.
 */
export async function buildCountryReport(
  ctx: AppContext,
  ref: CountryRef,
  yearFrom: number,
  yearTo: number,
  onProgress: (step: number, total: number, message: string) => Promise<void> = async () => {},
): Promise<string> {
  const TOTAL_STEPS = 5;
  const { citation } = await datasetProvenance(ctx, 'population');

  await onProgress(1, TOTAL_STEPS, 'Fetching displacement history');
  const { records: popRecords } = await fetchAllRows(ctx, {
    dataset: 'population',
    asylum_iso3: ref.iso3,
    yearFrom,
    yearTo,
  });
  const popAggregates = aggregateByYear(popRecords);
  const refugeeSeries = metricSeries(popAggregates, 'refugees');

  await onProgress(2, TOTAL_STEPS, 'Fetching origin breakdown');
  const latest = popAggregates.at(-1);
  let topOriginsTable = '_No data._';
  if (latest) {
    const { records } = await fetchAllRows(ctx, {
      dataset: 'population',
      asylum_iso3: ref.iso3,
      groupBy: 'origin',
      yearFrom: latest.year,
      yearTo: latest.year,
    });
    const top = records
      .filter((r) => r.origin && (r.metrics['refugees'] ?? 0) > 0)
      .sort((a, b) => (b.metrics['refugees'] ?? 0) - (a.metrics['refugees'] ?? 0))
      .slice(0, 8);
    if (top.length > 0) {
      topOriginsTable = markdownTable(
        ['Origin', 'Refugees'],
        top.map((r) => [r.origin ?? '', r.metrics['refugees'] ?? 0]),
      );
    }
  }

  await onProgress(3, TOTAL_STEPS, 'Fetching asylum figures');
  const { records: decisionRecords } = await fetchAllRows(ctx, {
    dataset: 'asylum-decisions',
    asylum_iso3: ref.iso3,
    yearFrom: Math.max(yearFrom, yearTo - 4),
    yearTo,
  });
  const decisionAggregates = aggregateByYear(decisionRecords);

  await onProgress(4, TOTAL_STEPS, 'Fetching demographics');
  const demo = await latestAggregates(ctx, 'demographics', { asylum_iso3: ref.iso3 });

  await onProgress(5, TOTAL_STEPS, 'Composing report');
  const regression = linearRegression(refugeeSeries);
  const changes = yearOverYear(refugeeSeries);
  const lastChange = changes.at(-1);

  const sections: string[] = [
    `# ${ref.name} — Humanitarian Situation Report`,
    '',
    `> Generated by humanitarian-mcp · Source: ${citation} · Range ${yearFrom}–${yearTo}`,
    '',
    '## Key figures',
  ];

  if (latest) {
    sections.push(
      markdownTable(
        ['Indicator', `People (${latest.year})`],
        Object.entries(latest.metrics).map(([k, v]) => [k, v]),
      ),
    );
  } else {
    sections.push('_No displacement data in range._');
  }

  sections.push('', '## Refugee population over time');
  if (refugeeSeries.length > 0) {
    sections.push(
      markdownTable(
        ['Year', 'Refugees'],
        refugeeSeries.map((p) => [String(p.year), p.value]),
      ),
      '',
      toMermaid({
        title: `Refugees hosted in ${ref.name}`,
        kind: 'line',
        xLabel: 'Year',
        yLabel: 'Refugees',
        series: [
          { label: ref.name, points: refugeeSeries.map((p) => ({ x: p.year, y: p.value })) },
        ],
      }),
      '',
      `Trend: ${regression.slope >= 0 ? 'increasing' : 'decreasing'} by ≈${formatNumber(Math.abs(Math.round(regression.slope)))} people/year (R²=${regression.r2.toFixed(2)}).` +
        (lastChange && lastChange.changePct !== null
          ? ` Last year-over-year change: ${lastChange.changePct.toFixed(1)}%.`
          : ''),
    );
  } else {
    sections.push('_No refugee data in range._');
  }

  sections.push('', '## Where refugees come from', topOriginsTable);

  sections.push('', '## Asylum decisions (last 5 years)');
  if (decisionAggregates.length > 0) {
    sections.push(
      markdownTable(
        ['Year', 'Recognized', 'Rejected', 'Closed', 'Total'],
        decisionAggregates.map((a) => [
          String(a.year),
          a.metrics['dec_recognized'] ?? 0,
          a.metrics['dec_rejected'] ?? 0,
          a.metrics['dec_closed'] ?? 0,
          a.metrics['dec_total'] ?? 0,
        ]),
      ),
    );
  } else {
    sections.push('_No asylum decision data in range._');
  }

  sections.push('', '## Demographics');
  if (demo) {
    const total = demo.metrics['total'] ?? 0;
    const fTotal = demo.metrics['f_total'] ?? 0;
    const children =
      (demo.metrics['f_0_4'] ?? 0) +
      (demo.metrics['f_5_11'] ?? 0) +
      (demo.metrics['f_12_17'] ?? 0) +
      (demo.metrics['m_0_4'] ?? 0) +
      (demo.metrics['m_5_11'] ?? 0) +
      (demo.metrics['m_12_17'] ?? 0);
    sections.push(
      `As of ${demo.year}: **${formatNumber(total)}** people of concern` +
        (total > 0
          ? `, ${((fTotal / total) * 100).toFixed(1)}% female, ${((children / total) * 100).toFixed(1)}% children (0–17).`
          : '.'),
    );
  } else {
    sections.push('_No recent demographic breakdown available._');
  }

  sections.push(
    '',
    '---',
    '_Method notes: figures are end-year stocks from UNHCR. "Total of concern" sums refugees, asylum-seekers, IDPs, stateless, others of concern and other people in need of international protection. Generated report — verify against unhcr.org/refugee-statistics before publication._',
  );

  return sections.join('\n');
}

export function registerReportTools(server: McpServer, ctx: AppContext): void {
  defineTool(
    server,
    ctx,
    'generate_country_report',
    {
      title: 'Generate country report',
      description:
        'Compose a full markdown humanitarian situation report for a country: key figures, refugee trend with an embedded chart, origins of hosted refugees, asylum decisions and demographics. Reports progress while assembling.',
      inputSchema: {
        country: countryInput,
        year_from: yearFromInput,
        year_to: yearToInput,
      },
      outputSchema: {
        country: z.string(),
        country_code: z.string(),
        year_from: z.number(),
        year_to: z.number(),
        markdown: z.string(),
      },
    },
    async ({ country, year_from, year_to }, extra) => {
      const ref = await resolveCountry(ctx, country);
      const { yearFrom, yearTo } = defaultYearRange(year_from, year_to);

      const markdown = await buildCountryReport(
        ctx,
        ref,
        yearFrom,
        yearTo,
        (step, total, message) => reportProgress(extra, step, total, message),
      );

      return {
        content: [{ type: 'text', text: markdown }],
        structuredContent: {
          country: ref.name,
          country_code: ref.iso3,
          year_from: yearFrom,
          year_to: yearTo,
          markdown,
        },
      };
    },
  );
}
